SavandBros/gonevis-dash-2

src/app/services/api/api.service.spec.ts, src/app/services/api/api.service.ts, src/environments/environment.prod.ts, src/environments/environment.ts
=> Resolve "Setup API service"

src/app/app.component.html, src/app/app.component.ts, src/app/app.module.ts, src/app/interfaces/user-auth.ts, src/app/interfaces/user-blog.ts, src/app/services/auth/auth.service.ts
=> Resolve "Setup global navbar"

src/app/components/sign-in/sign-in.component.html, src/app/components/sign-in/sign-in.component.ts
=> Resolve "Design sign in page"

src/app/components/sign-up/sign-up.component.html, src/app/components/sign-up/sign-up.component.ts
=> Resolve "Design sign up page"

src/app/components/sign-up/sign-up.component.html
=> Resolve "Sign up translation UI slow"

src/app/services/auth/auth.service.ts
=> Resolve "Sign user in (via service) after signing up"

src/app/components/feed/feed.component.html, src/app/components/feed/feed.component.scss, src/app/components/feed/feed.component.ts, src/app/components/feed/feed.module.ts, src/app/components/feed/feed.service.spec.ts, src/app/components/feed/feed.service.ts, src/assets/i18n/en.json, src/styles.scss
=> Resolve "Design feed"

src/app/services/auth/auth.service.ts
=> Resolve "Handle invalid token on reset password"

src/app/components/sign-in/sign-in.component.ts
=> Resolve "Redirect to feed when sign in"

src/app/services/auth-interceptor/auth-interceptor.service.ts, src/app/services/auth/auth.service.ts
=> Resolve "Sign out user on 403 response"

src/app/components/feed/entry/entry.component.html, src/app/components/feed/entry/entry.component.scss, src/app/components/feed/entry/entry.component.ts, src/app/components/feed/entry/entry.module.ts, src/app/interfaces/blog-minimal-feed.ts, src/app/interfaces/comment-feed.ts, src/app/interfaces/entry-feed.ts, src/app/interfaces/media.ts, src/app/interfaces/user-auth.ts, src/app/services/comment/comment.service.spec.ts, src/app/services/comment/comment.service.ts, src/app/services/entry/entry.service.ts, src/app/shared/comment-form/comment-form.component.html, src/app/shared/comment-form/comment-form.component.spec.ts, src/app/shared/comment-form/comment-form.component.ts, src/app/shared/comment-form/comment-form.module.ts, src/app/shared/entry-list/entry-list.component.html, src/app/shared/entry-list/entry-list.component.ts, src/assets/i18n/en.json
=> Resolve "Add comment like, edit and delete"

src/app/components/feed/blog/blog-routing.module.ts, src/app/components/feed/blog/blog.component.html, src/app/components/feed/blog/blog.component.spec.ts, src/app/components/feed/blog/blog.component.ts, src/app/components/feed/blog/blog.module.ts, src/app/components/feed/blog/blog.service.spec.ts, src/app/components/feed/blog/blog.service.ts, src/app/components/feed/feed-routing.module.ts, src/app/interfaces/blog-feed.ts, src/app/interfaces/comment-feed.ts, src/app/shared/entry-list/entry-list.component.html
=> Resolve "Setup blog detail page"

src/app/components/feed/entry/entry.component.html, src/app/components/feed/entry/entry.component.ts, src/app/components/feed/feed.component.ts, src/app/interfaces/comment-form-event.ts, src/app/shared/comment-form/comment-form.component.html, src/app/shared/comment-form/comment-form.component.ts
=> Resolve "Improve comment form"

src/app/app-routing.module.ts, src/app/components/dash/dash-routing.module.ts, src/app/components/dash/dash.component.html, src/app/components/dash/dash.component.spec.ts, src/app/components/dash/dash.component.ts, src/app/components/dash/dash.module.ts, src/app/components/dash/team/team-routing.module.ts, src/app/components/dash/team/team.component.html, src/app/components/dash/team/team.component.spec.ts, src/app/components/dash/team/team.component.ts, src/app/components/dash/team/team.module.ts, src/app/components/dash/team/team.service.spec.ts, src/app/components/dash/team/team.service.ts, src/app/enums/team-roles.ts, src/app/interfaces/params-object.ts, src/app/interfaces/params.ts, src/app/interfaces/team-member.ts, src/app/interfaces/team.ts, src/app/interfaces/user-team.ts, src/app/services/auth/auth.service.ts, src/app/services/blog/blog.service.spec.ts, src/app/services/blog/blog.service.ts, src/assets/i18n/en.json
=> Resolve "Setup dashboard page"

src/app/components/user/user-setting/user-password/user-password.component.html, src/app/components/user/user-setting/user-password/user-password.module.ts, src/app/interfaces/password-strength.ts, src/app/shared/password-strength/password-strength.component.html, src/app/shared/password-strength/password-strength.component.spec.ts, src/app/shared/password-strength/password-strength.component.ts, src/app/shared/password-strength/password-strength.module.ts
=> Resolve "Add Password strength checker"

src/app/components/dash/team/team.component.html, src/app/components/dash/team/team.component.ts, src/app/components/dash/team/team.module.ts, src/app/components/dash/team/team.service.ts, src/assets/i18n/en.json
=> Invite member

src/app/app.component.ts
=> Add a method to check whether user is in any dash page or not

src/app/services/util/util.service.ts, src/app/shared/entry-list/entry-list.component.html, src/app/shared/entry-list/entry-list.component.ts
=> Fix embed and iFrames getting re-attached to DOM on scroll

src/app/components/dash/main/main.component.html
=> Polish main

src/app/components/feed/blog/blog.component.ts, src/app/components/feed/feed.service.ts, src/app/components/feed/reader/reader.component.ts, src/app/components/feed/user/user.component.ts
Fixes #133 
https://bros.zepel.io/projects/8e893259-4c56-417c-b53b-cf00e4e0c232/lists/405f3ee0-f1c5-4fc0-a617-9b8d962388bd/items/656c3a31-1aed-418b-9655-64d2152237b9
=> Fix API endpoints on feed

src/app/shared/embed/embed.directive.spec.ts, src/app/shared/embed/embed.directive.ts, src/app/shared/embed/embed.module.ts, src/app/shared/entry-list/entry-list.component.html, src/app/shared/entry-list/entry-list.component.ts, src/app/shared/entry-list/entry-list.module.ts
https://bros.zepel.io/projects/8e893259-4c56-417c-b53b-cf00e4e0c232/lists/405f3ee0-f1c5-4fc0-a617-9b8d962388bd/items/e1a35f2a-ddc4-4ba1-8fb6-c06842b69b43
=> Resolve "Render entry excerpts as HTML"

src/app/app.component.html, src/app/components/dash/dash.component.scss, src/assets/styles/gonevis.scss
https://bros.zepel.io/projects/8e893259-4c56-417c-b53b-cf00e4e0c232/lists/405f3ee0-f1c5-4fc0-a617-9b8d962388bd/items/769e80f8-7e9e-44a3-a8fc-a6baa256d241
=> Fix navbar on scroll

src/app/components/dash/team/team.component.html
https://bros.zepel.io/projects/8e893259-4c56-417c-b53b-cf00e4e0c232/lists/405f3ee0-f1c5-4fc0-a617-9b8d962388bd/items/4583d081-7582-47c3-99f3-a2425567b4bc
=> Fix team invitation form error

src/app/components/dash/comments/comments.component.html, src/app/components/dash/comments/comments.component.ts, src/app/components/dash/comments/comments.module.ts, src/app/components/dash/comments/comments.service.ts, src/app/components/dash/media/media.service.ts, src/app/components/dash/tags/tags.component.html, src/app/components/dash/tags/tags.component.ts, src/app/components/dash/tags/tags.module.ts, src/app/components/dash/tags/tags.service.ts, src/app/shared/file-list/file-list.component.html, src/app/shared/file-list/file-list.component.ts, src/app/shared/file-list/file-list.module.ts
https://bros.zepel.io/projects/8e893259-4c56-417c-b53b-cf00e4e0c232/lists/405f3ee0-f1c5-4fc0-a617-9b8d962388bd/items/8eb8ded8-054e-4160-9803-6e7e006be907
=> Add pagination to pages

src/app/components/dash/tags/tags.component.html, src/app/components/dash/team/team.component.html, src/app/shared/tags-modal/tag-modal.component.html, src/assets/i18n/en.json
https://bros.zepel.io/projects/8e893259-4c56-417c-b53b-cf00e4e0c232/lists/405f3ee0-f1c5-4fc0-a617-9b8d962388bd/items/cadac090-0e4d-4022-82d3-cc07db3cdf9c
=> Add label to tag and team invite form (edit and create)

src/app/components/dash/tags/tags.component.html, src/app/components/dash/tags/tags.component.ts, src/app/components/dash/tags/tags.module.ts, src/app/interfaces/v1/tag.ts, src/app/shared/tags-modal/tag-modal.component.html, src/app/shared/tags-modal/tag-modal.component.ts, src/app/shared/tags-modal/tag-modal.module.ts, src/assets/i18n/en.json
https://bros.zepel.io/projects/8e893259-4c56-417c-b53b-cf00e4e0c232/lists/405f3ee0-f1c5-4fc0-a617-9b8d962388bd/items/38a445f8-001e-4749-9c2b-ae5935b57541
=> Add cover image for tags

src/app/services/auth-guard/auth-guard.service.ts, src/app/services/auth/auth.service.ts
https://bros.zepel.io/projects/8e893259-4c56-417c-b53b-cf00e4e0c232/lists/405f3ee0-f1c5-4fc0-a617-9b8d962388bd/items/6b44c4c6-0915-4d67-88e0-6461aa55740f
=> Redirect user on app visit

src/app/app.component.html, src/app/components/feed/entry/entry.component.html, src/app/components/feed/entry/entry.component.ts, src/app/components/feed/user/user.component.ts, src/app/shared/blog-list/blog-list.component.html, src/app/shared/comment-form/comment-form.component.html, src/app/shared/comment-form/comment-form.component.ts, src/app/shared/entry-list/entry-list.component.html
Resolves: https://bros.zepel.io/projects/8e893259-4c56-417c-b53b-cf00e4e0c232/lists/405f3ee0-f1c5-4fc0-a617-9b8d962388bd/items/e60fe02a-cd2a-42b5-b215-fcd35d28dac3
Resolves: https://bros.zepel.io/projects/8e893259-4c56-417c-b53b-cf00e4e0c232/lists/405f3ee0-f1c5-4fc0-a617-9b8d962388bd/items/6f376bf0-c812-480f-a2a1-46a93c302663
Resolves: https://bros.zepel.io/projects/8e893259-4c56-417c-b53b-cf00e4e0c232/lists/405f3ee0-f1c5-4fc0-a617-9b8d962388bd/items/7c27c1ff-1290-4d67-a91a-77dbdb217839
=> Updating feed (commenting, scroll for posts)

package-lock.json, package.json, src/app/app.module.ts, src/app/interfaces/environment.ts, src/environments/environment.prod.ts, src/environments/environment.production.ts, src/environments/environment.stag.ts, src/environments/environment.ts
Resolves https://bros.zepel.io/projects/8e893259-4c56-417c-b53b-cf00e4e0c232/lists/405f3ee0-f1c5-4fc0-a617-9b8d962388bd/items/7c9466a0-c214-402e-bbbd-874150113197
=> Setup google analytics

src/app/components/dash/dash.component.html, src/app/components/dash/dash.component.scss, src/app/components/dash/dash.component.ts, src/assets/i18n/en.json
Resolve https://bros.zepel.io/projects/8e893259-4c56-417c-b53b-cf00e4e0c232/lists/405f3ee0-f1c5-4fc0-a617-9b8d962388bd/items/c71158c9-9cd8-43c5-a50b-8e7f8829958e
=> Add sidebar close button

src/app/app.component.html, src/app/app.component.ts, src/app/components/dash/dash.component.ts, src/app/services/blog/blog.service.ts
Resolve https://bros.zepel.io/projects/8e893259-4c56-417c-b53b-cf00e4e0c232/lists/405f3ee0-f1c5-4fc0-a617-9b8d962388bd/items/bc0bbc77-dfaa-4cf8-80b0-ddc25b7509b7
=> Invalid blog index in URL doesn't change the URL

src/app/components/dash/write/write.component.html, src/app/components/dash/write/write.component.ts, src/environments/environment.production.ts
Resolve: https://bros.zepel.io/projects/8e893259-4c56-417c-b53b-cf00e4e0c232/lists/405f3ee0-f1c5-4fc0-a617-9b8d962388bd/items/0bc97241-d8fc-4c07-b9a0-b3e4d6bec59d
=> Fix production issues

src/app/components/dash/navs/navs.component.html, src/app/components/dash/navs/navs.component.ts, src/app/components/dash/navs/navs.module.ts, src/app/components/dash/settings/settings.component.html, src/app/components/dash/settings/settings.component.ts, src/app/components/dash/settings/settings.module.ts, src/app/components/dash/team/team.component.html, src/app/components/dash/team/team.component.ts, src/app/components/dash/team/team.module.ts, src/app/shared/permission-access/permission-access.component.html, src/app/shared/permission-access/permission-access.component.spec.ts, src/app/shared/permission-access/permission-access.component.ts, src/app/shared/permission-access/permission-access.module.ts
=> Add permission access handler

src/app/components/user/email-confirmation/email-confirmation.component.html, src/app/components/user/email-confirmation/email-confirmation.component.ts, src/app/components/user/email-confirmation/email-confirmation.module.ts, src/assets/i18n/en.json
=> Update email verification page to show loading and error.

src/app/components/dash/entry/entry.service.ts, src/app/components/dash/main/main.component.html, src/app/components/dash/main/main.component.ts, src/app/components/dash/main/main.module.ts, src/app/interfaces/reactive-form-data.ts, src/assets/i18n/en.json, src/assets/styles/gonevis.scss
A panel to quickly write and save a draft:
When the input has value (user writes) the save button appears:
Toast on creation:
Quick draft title:
=> Quick draft

src/app/shared/entry-list/entry-list.component.html, src/app/shared/entry-list/entry-list.component.ts, src/app/shared/entry-list/entry-list.module.ts
Can we not have it for the dash only?
=> Show excerpt as text not HTML

src/app/components/dash/dash.component.ts, src/app/components/dash/write/write.component.html, src/app/components/dash/write/write.component.ts, src/app/interfaces/v1/entry.ts
=> Send/receive tag's slug instead of their ids

src/app/app-routing.module.ts, src/app/components/dash/dash-guard.service.ts, src/app/services/auth-guard/auth-guard.service.ts, src/app/services/auth/auth.service.ts
=> Error when accessing dash page when unauthenticated

src/assets/styles/gonevis.scss
=> Update editor's typography

src/app/components/dash/dash.component.ts, src/app/components/user/start/start.component.ts, src/app/services/blog/blog.service.ts
=> Fix current blog after blog creation

src/app/components/dash/comments/comments.service.ts, src/app/components/dash/entry/entry.service.ts, src/app/components/dash/main/main.component.ts, src/app/components/dash/media/media.service.ts, src/app/components/dash/navs/navs.service.ts, src/app/components/dash/settings/settings-billing/settings-billing.service.ts, src/app/components/dash/settings/settings-upgrade/settings-upgrade.service.ts, src/app/components/dash/tags/tags.service.ts, src/app/components/dash/team/team.service.ts, src/app/components/dash/write/write.service.ts, src/app/components/feed/blog/blog.service.ts, src/app/components/feed/feed.component.ts, src/app/services/blog/blog.service.ts
=> Change all v1 endpoints

src/app/components/dash/comments/comments.service.ts, src/app/components/dash/entry/entry.service.ts, src/app/components/dash/media/media.service.ts, src/app/components/dash/navs/navs.service.ts, src/app/components/dash/settings/settings-advanced/settings-advanced.component.html, src/app/components/dash/settings/settings-advanced/settings-advanced.component.ts, src/app/components/dash/settings/settings-billing/settings-billing.service.ts, src/app/components/dash/settings/settings-general/settings-general.component.html, src/app/components/dash/settings/settings-general/settings-general.component.ts, src/app/components/dash/settings/settings-upgrade/settings-upgrade.component.ts, src/app/components/dash/settings/settings-upgrade/settings-upgrade.service.ts, src/app/components/dash/settings/settings.module.ts, src/app/components/dash/tags/tags.service.ts, src/app/components/dash/team/team.service.ts, src/app/components/dash/write/write.service.ts, src/app/components/feed/blog/blog.service.ts, src/app/components/feed/feed.component.ts, src/app/services/blog/blog.service.ts, src/app/shared/locked-feature/locked-feature.component.html, src/app/shared/locked-feature/locked-feature.component.scss, src/app/shared/locked-feature/locked-feature.component.ts, src/app/shared/locked-feature/locked-feature.module.ts, src/app/shared/locked-feature/shared/enums/plan.ts, src/app/shared/locked-feature/shared/interfaces/plan-data.ts, src/assets/i18n/en.json
Have more plans for this topic, but for now, this should be a good start.
Depends on: https://github.com/SavandBros/gonevis-dash-2/pull/226
=> Locked Features UI

src/app/components/dash/settings/settings-appearance/settings-appearance.component.html, src/app/components/dash/tags/tags.component.html, src/app/shared/feedback-modal/feedback-modal.component.html, src/app/shared/file-selection/file-selection.component.html, src/app/shared/tags-modal/tag-modal.component.html, src/assets/styles/gonevis.scss
=> Update default UI of modals and toasts

src/app/components/dash/write/write.component.ts, src/polyfills.ts
=> Fix YouTube video embedding is broken

src/app/components/feed/blog/blog.service.ts
=> Fix feed blog page not showing results in Edge browser

src/app/components/feed/entry/entry.component.ts, src/app/services/comment/comment.service.ts
=> Fix voting and removing comments not working

src/app/shared/feedback-modal/feedback-modal.component.html, src/app/shared/feedback-modal/feedback-modal.component.scss, src/app/shared/feedback-modal/feedback-modal.component.ts, src/app/shared/feedback-modal/feedback-modal.module.ts, src/assets/i18n/en.json
=> Resolve "Add subject and reaction to feedback"

src/app/services/comment/comment.service.ts
=> Resolve "Update commenting API"

src/app/components/feed/entry/entry.component.ts, src/app/interfaces/zero/feed/comment-vote-response.ts, src/app/services/comment/comment.service.ts
=> Comment voting API update

src/app/shared/file-list/file-list.component.html, src/app/shared/file-list/file-list.component.ts, src/app/shared/file-selection/file-selection.component.html, src/app/shared/pagination/pagination.component.html, src/app/shared/pagination/pagination.component.ts
=> Show only images at file selection modal and hide media type selection and remove unwanted spaces

src/app/shared/file-list/file-list.component.ts, src/app/shared/file-selection/file-selection.component.ts
=> Resolve "Fix uploaded file not showing up"

README.md, package.json, scripts/changelog.js, scripts/core/slugify.js
=> Resolve "Add the lovey changelog npm command"

src/app/components/dash/settings/appearance/appearance.component.html, src/assets/i18n/en.json
Resolves #364 
* The issue for fixing height of theme selection is not solved in this pull request.
=> Resolve "Fix and rename sections of settings"

src/app/app.component.html
=> Resolve "After sign up you see dash link instead of feed at navbar"

src/app/components/dash/entry/entry.component.html, src/app/components/dash/entry/entry.component.ts, src/app/components/dash/write/write.component.ts, src/assets/i18n/en.json, src/assets/styles/gonevis.scss
=> Resolve "Add create button for pages and posts"

src/app/components/dash/write/write.component.ts
=> Resolve "Fix lint issue in write component"

changelogs/feature-399-add-statistics-page-to-dashboard.json, e2e/src/dash/statistics/statistics.e2e-spec.ts, e2e/src/dash/statistics/statistics.po.ts, src/app/components/dash/dash-routing.module.ts, src/app/components/dash/dash.component.ts, src/app/components/dash/statistics/statistics-routing.module.ts, src/app/components/dash/statistics/statistics.component.html, src/app/components/dash/statistics/statistics.component.scss, src/app/components/dash/statistics/statistics.component.ts, src/app/components/dash/statistics/statistics.module.ts, src/app/shared/metric-stat-chart-line/metric-stat-chart-line.module.ts, src/app/shared/pagination/pagination.module.ts, src/app/shared/post-panel/post-panel.module.ts
=> Resolve "Add statistics page to dashboard"

.circleci/config.yml, angular.json, changelogs/fix-408-remove-highlightjs-from-editor.json, changelogs/improvement-406-remove-editorscss-globally.json, package-lock.json, package.json, src/app/components/dash/write/write-routing.module.ts, src/app/components/dash/write/write.component.scss, src/app/components/dash/write/write.component.ts, src/assets/styles/editor.scss, src/assets/styles/gonevis.scss
Closes #408 
Closes #406 
Closes #407
=> Resolves: remove highlightjs and lazyload editor scss

changelogs/fix-414-fix-embeds-not-working-properly-in-editor.json, src/app/components/dash/write/write.component.ts
=> Resolves "Fix embeds not working properly in editor"

changelogs/fix-413-update-button-colors-to-match-current-theme-at-editor.json, src/app/components/dash/write/write.component.scss
=> Resolves "Update button colors to match current theme at editor"

changelogs/fix-444-fix-blog-logo-overrided-description-on-feed.json, changelogs/improvement-339-add-external-link-for-feed-content.json, changelogs/improvement-445-change-follow-button-ui-on-feed.json, changelogs/improvement-447-change-post-share-link-to-external-link.json, src/app/components/feed/user/user.component.html, src/app/interfaces/user.ts, src/app/shared/blog-list/blog-list.component.html, src/app/shared/blog-list/blog-list.component.ts, src/app/shared/blog-list/blog-list.module.ts, src/app/shared/entry-list/entry-list.component.html, src/app/shared/entry-list/entry-list.component.ts, src/app/shared/share/share.component.ts, src/assets/i18n/en.json, src/assets/styles/gonevis.scss
=> UI/UX Updates

changelogs/improvement-451-add-tabs-for-different-entry-statuses-instead-of-dropdown-selection.json, src/app/components/dash/entry/entry.component.html, src/app/components/dash/entry/entry.component.ts, src/assets/i18n/en.json
=> Resolves "Add tabs for different entry statuses instead of dropdown selection"

changelogs/fix-455-fix-editor-auto-save-and-keybindings-working-even-after-page-is-destroyed.json, changelogs/improvement-457-auto-save-entry-after-the-user-leaves-page-by-navigation.json, src/app/components/dash/write/write.component.ts
=> Resolves "Cannot read property 'id' of undefined"

changelogs/fix-458-fix-page-not-scrolling-up-when-navigating-to-feed-user-page.json, src/app/components/feed/user/user.component.ts
=> Resolves "Fix page not scrolling up when navigating to feed user page.

changelogs/improvement-466-show-any-status-comments-on-dashboard.json, src/app/components/dash/comments/comments.component.ts
=> Resolve "Show any status comments on dashboard"

changelogs/fix-477-fix-statistics-page-doesnt-work.json, src/app/components/dash/statistics/statistics.component.html, src/app/components/dash/statistics/statistics.component.ts
=> Resolve "Fix statistics page doesn't work"

changelogs/fix-494-fix-editor-get-tags-with-extra-site-id-query-params.json, src/app/components/dash/write/write.service.ts
=> Resolves "Fix editor GET tags with extra site ID query params"

changelogs/fix-518-show-an-error-when-404-raises-in-editor-page.json, src/app/components/dash/write/write.component.html, src/app/components/dash/write/write.component.ts, src/assets/i18n/en.json
=> Resolves "Show an error when 404 raises in Editor page"
